name: CD Example Production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: CD Example Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH Connect
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            echo "Berhasil Connect ke Server"
            if [ -d "/home/dul" ]; then
              echo "Folder /home/dul ditemukan"
              cd /home/dul
              echo "Berhasil Masuk ke Folder"
            else
              echo "Folder /home/dul tidak ditemukan, membuat folder..."
              sudo mkdir /home/dul
              echo "Berhasil Masuk ke Folder"
              cd /home/dul
            fi

            if [ -d ".git" ]; then
              echo "📦 Repo exists, pulling latest changes..."
              
                git remote set-url origin https://github.com/akuazizz/MKEPL-DATABASE.git
                git pull origin main
            else
                echo "📦 Cloning repo for the first time..."
                git clone https://github.com/akuazizz/MKEPL-DATABASE.git
            fi

            echo "✅ Deployment finished at $(date)"