name: CICD Database Dev to Prod
on:
  push:
    branches:
      - main

jobs:
  db_cicd:
    name: Database CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  My Code
        uses: actions/checkout@v4 #checkout the code from the repository

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1 # SSH action to run commands on a remote server
        with:
          host: ${{ secrets.SERVER_HOST }} # The remote server's IP address or hostname
          username: ${{ secrets.SERVER_USER }} # The username to log in to the remote server
          password: ${{ secrets.SERVER_PASSWORD }} # The password for the remote server
          port: ${{ secrets.PORT }}
          script: |
            echo "Berhasil Connect ke Server"

            cd /home/dul/MKEPL-DATABASE
            echo "Berhasil Masuk ke Folder"

            sudo docker compose up -d # Start the Docker containers in detached mode
            echo "Berhasil Jalankan Docker Compose"

            # CI (Continuous Integration) untuk Database
            echo "Menunggu Server MySQL Siap"
            sleep 30 # Wait for 30 seconds to ensure MySQL is ready

            sudo docker exec -i mysql_prod_container mysql -uroot -pTelkom123! -e "SHOW DATABASES;" # Show databases in MySQL
